### ISSUE TITLE
Smart Battery Sense

### ISSUE THREAD

**Issue by pirateyachty** [stefanor/signalk-victron-ble#7]
Maybe I am doing something wrong.  I have all (8) of my MPPT controllers showing up in Signalk which is awesome however when I paired the Smart Battery Sense it throws up errors in the log.  I guess I have to get a smart shunt instead.

**Comment by pirateyachty** [comment]
Thank you for replying
This is the error from the log please let me know if there is a better or more more detailed log file you need.

Jul 25 09:47:53 ERROR:root:A message handler raised an exception: 'BatterySenseData' object has no attribute 'get_current'. Traceback (most recent call last): File "/home/pirateyachty/.signalk/node_modules/signalk-victron-ble/ve/lib/python3.9/site-packages/dbus_fast/message_bus.py", line 811, in _process_message result = user_handler(msg) File "/home/pirateyachty/.signalk/node_modules/signalk-victron-ble/ve/lib/python3.9/site-packages/bleak/backends/bluezdbus/manager.py", line 848, in _parse_msg self._run_advertisement_callbacks( File "/home/pirateyachty/.signalk/node_modules/signalk-victron-ble/ve/lib/python3.9/site-packages/bleak/backends/bluezdbus/manager.py", line 892, in _run_advertisement_callbacks callback(device_path, device.copy()) File "/home/pirateyachty/.signalk/node_modules/signalk-victron-ble/ve/lib/python3.9/site-packages/bleak/backends/bluezdbus/scanner.py", line 279, in _handle_advertising_data self._callback(device, advertisement_data) File "/home/pirateyachty/.signalk/node_modules/signalk-victron-ble/ve/lib/python3.9/site-packages/victron_ble/scanner.py", line 39, in _detection_callback self.callback(device, data) File "/home/pirateyachty/.signalk/node_modules/signalk-victron-ble/plugin.py", line 58, in callback delta = transformer(bl_device, configured_device, data, id_) File "/home/pirateyachty/.signalk/node_modules/signalk-victron-ble/plugin.py", line 80, in transform_battery_data "value": data.get_current(), AttributeError: 'BatterySenseData' object has no attribute ‘get_current'


Thank you
